name: Deploy React Frontend to VPS

on:
  push:
    branches:
      - main # Hoặc branch bạn muốn CI/CD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟨 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm install
        working-directory: font-devop

      - name: 🔨 Build React app
        run: npm run build
        working-directory: font-devop

      - name: 📡 Deploy via SSH (upload dist to VPS)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          source: "font-devop/dist/*"
          target: "${{ secrets.VPS_FE_PATH }}/dist"
          strip_components: 2

      - name: ✅ Done!
        run: echo "Frontend deployed to VPS successfully!"
